### ISSUE TITLE
Clarify requirement of network access with docker-compose.yml

### ISSUE THREAD

**Issue by activenode** [dotmesh-io/dotmesh#287]
**WHAT IS THE ISSUE?**
I tried the docker-compose.yml tutorial given in https://docs.dotmesh.com/tasks/docker-compose/#docker-compose-v2-and-v3

When you apply this to an _existing_ docker-compose.yml which contains an independent bridged network definition the `dm list` command will show the volume but the related container section "CONTAINERS" is empty and also every action on the container is not tracked / blackholed.

Example:
docker-compose.yml:

```
version: '3.2'

volumes:
    dmable.mysql:
        driver: dm

services:
  dbserver:
    image: 'mariadb:latest'
    volumes:
      - "dmable.mysql:/var/lib/mysql"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
```

I am aware of the fact that this is not a "bug" by definition however it's not clear how `dm` exactly works so one has to guess the issue behind.

**A solution that works but might not be clean:**
E.g. I just added the "dm containers" to the network via `docker network connect mynetwork dotmesh-whatever-container` (for all dm containers) which I don't find is a clean solution (at least as long as it is not officially confirmed that this is _the_ solution).

So can you please clarify this usage?

**EXPECTED:**
Clarify the official way to use `dotmesh` in combination with networking.

**Comment by lukemarsden** [comment]
Thanks for the bug report @activenode!

We're looking into whether we can reproduce this, and will update this ticket with more details soon.

**Comment by alaric-datamesh** [comment]
I can't reproduce this. I've got docker-compose version 1.10.0 to hand so had to change the version in the YAML to `3.0` to get it to load, and then I had to add an environment variable to get MariaDB to not complain like so:

```
dbserver_1  | error: database is uninitialized and password option is not specified 
dbserver_1  |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

Which meant I ran with this:

```yaml
version: '3.0'

volumes:
    dmable.mysql:
        driver: dm

services:
  dbserver:
    image: 'mariadb:latest'
    volumes:
      - "dmable.mysql:/var/lib/mysql"
    networks:
      - mynetwork
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

networks:
  mynetwork:
    driver: bridge
```

And then `docker-compose up` worked, and I get:

```
$  dm list
Current remote: local (use 'dm remote -v' to list and 'dm remote switch' to switch)

  DOT         BRANCH  SERVER            CONTAINERS       SIZE        COMMITS  DIRTY
* tmp_dmable  master  1df6bd31e7a2c31a  /tmp_dbserver_1  114.35 MiB  0        114.35 MiB  
```

This is as I would have expected (I was in my `~/tmp` directory). Dotmesh shouldn't need to have network connectivity to the containers mounting volumes from dots - there's network traffic from `dm` to the `dotmesh-server-inner` container, and between `dotmesh-server-inner` containers on different nodes in a cluster, and to/from other clusters such as the Hub if you push and pull; but the connection between `dotmesh-server-inner` and your own containers is purely that `dotmesh-server-inner` sets up a filesystem mountpoint for the volume and hands the path over to Docker, which then mounts it into your container via the facilities provided by the kernel.

So, we need to figure out what's happening in your situation. Can I ask you to do a few tests for me?

1. Try a `dm init testdot` followed by `dm list` to see if the basics work.
2. `docker run -v testdot2:/test --volume-driver dm busybox touch /test/hello` followed by `dm list` to see if Docker mounts are working and creating dots OK.

Thanks!
